from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name='superhome'),
    path('busadminregister/', views.BusRegisterPage, name='busregister'),
    path('trainadminregister/', views.TrainRegisterPage, name='trainregister'),
    path('busadmindetails/', views.BusAdminPage, name='busadminr'),
    path('trainadmindetails/', views.TrainAdminPage, name='trainadminr'),
    path('schoolregister/', views.SchoolRegisterPage, name='schoolregister'),
    path('school/', views.SchoolPage, name='school'),
    path('trainplace/', views.TrainPlacePage, name='trainplace'),
    path('trainroute/', views.TrainRoutePage, name='trainroute'),
    path('traintime/', views.TrainSubTimes, name='traintime'),
    path('bustime/', views.BusSubTimes, name='bustime'),
    path('tpass/', views.TPassPage, name='tpass'),
    path('bpass/', views.BPassPage, name='bpass'),
    path('tspass/', views.TSPassPage, name='tspass'),
    path('bpassedit/<str:pk>/', views.BPassEditPage, name='bpassedit'),
    path('tpassedit/<str:pk>/', views.TPassEditPage, name='tpassedit'),
    path('tspassedit/<str:pk>/', views.TSPassEditPage, name='tspassedit'),
    path('deletebpass/<str:pk>/', views.DeleteBPass, name='deletebpass'),
    path('deletetpass/<str:pk>/', views.DeleteTPass, name='deletetpass'),
    path('deletetspass/<str:pk>/', views.DeleteTSPass, name='deletetspass'),
    path('busplace/', views.BusPlacePage, name='busplace'),
    path('busplaceregister/', views.BusPlaceRegister, name='busplaceregister'),
    path('trainplaceregister/', views.TrainPlaceRegister, name='trainplaceregister'),
    path('schooledit/<str:pk>/', views.SchoolEditPage, name='schooledit'),
    path('busplaceedit/<str:pk>/', views.BusPlaceEditPage, name='busplaceedit'),
    path('trainrouteregister/', views.TrainRouteRegister, name='trainrouteregister'),
    path('traintimeregister/', views.TrainTimeRegister, name='traintimeregister'),
    path('bustimeregister/', views.BusTimeRegister, name='bustimeregister'),
    path('trainplaceedit/<str:pk>/', views.TrainPlaceEditPage, name='trainplaceedit'),
    path('trainrouteedit/<str:pk>/', views.TrainRouteEditPage, name='trainrouteedit'),
    path('traintimeedit/<str:pk>/', views.TrainTimeEditPage, name='traintimeedit'),
    path('bustimeedit/<str:pk>/', views.BusTimeEditPage, name='bustimeedit'),
    path('deletetrainroute/<str:pk>/', views.DeleteTrainRoute, name='deletetrainroute'),
    path('deletetraintime/<str:pk>/', views.DeleteTrainTime, name='deletetraintime'),
    path('deletebustime/<str:pk>/', views.DeleteBusTime, name='deletebustime'),
    path('trainedit/<str:pk>/', views.TrainEditPage, name='trainedit'),
    path('busedit/<str:pk>/', views.BusEditPage, name='busedit'),
    path('deletetrainplace/<str:pk>/', views.DeleteTrainPlace, name='deletetrainplace'),
    path('deletebusplace/<str:pk>/', views.DeleteBusPlace, name='deletebusplace'),
    path('deletebus/<str:pk>/', views.DeleteBusAdmin, name='deletebus'),
    path('deletetrain/<str:pk>/', views.DeleteTrainAdmin, name='deletetrain'),
    path('deleteschool/<str:pk>/', views.DeleteSchool, name='deleteschool'),
]