# Generated by Django 4.0.5 on 2022-10-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
