# Generated by Django 4.0.5 on 2022-10-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_last_login_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_logout_time',
        ),
    ]
