# Generated by Django 4.0.5 on 2022-10-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_last_logout_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_time',
        ),
    ]
