# Generated by Django 4.1.2 on 2022-10-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_customuser_last_login_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="gender",),
    ]
