# Generated by Django 4.0.5 on 2022-10-16 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0009_delete_schooldetail_remove_subtime_sub_price_and_more'),
        ('ksrtc', '0026_delete_schooldetail_remove_subtime_sub_price_and_more'),
        ('adminapp', '0008_schooldetail'),
        ('users', '0007_remove_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_school', to='adminapp.schooldetail'),
        ),
        migrations.CreateModel(
            name='TrainVirtualPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('log_check', models.BooleanField(default=False, null=True)),
                ('end_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_place_pass', to='irctc.place')),
                ('start_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_place_pass', to='irctc.place')),
            ],
        ),
        migrations.CreateModel(
            name='BusVirtualPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('log_check', models.BooleanField(default=False, null=True)),
                ('end_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_place_pass', to='ksrtc.place')),
                ('start_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_place_pass', to='ksrtc.place')),
            ],
        ),
    ]
