# Generated by Django 4.1.2 on 2023-03-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_customuser_school_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyBusPassView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_date", models.DateField()),
                ("today", models.DateField()),
                ("checkbox1", models.BooleanField(default=False)),
                ("checkbox2", models.BooleanField(default=False)),
            ],
        ),
    ]
