# Generated by Django 4.1.2 on 2023-03-27 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0055_passform_end_date"),
        ("users", "0010_dailybuspassview"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailybuspassview",
            name="pass_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ksrtc.passform",
            ),
        ),
    ]
