# Generated by Django 4.0.5 on 2022-10-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(blank=True, max_length=100, null=True)),
                ('districts', models.CharField(blank=True, max_length=255, null=True)),
                ('from_place', models.CharField(blank=True, max_length=100, null=True)),
                ('to_place', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
