# Generated by Django 4.0.5 on 2022-10-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0002_remove_trainroutes_to_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainroutes',
            name='to_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
