# Generated by Django 4.0.5 on 2022-10-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0003_trainroutes_to_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainRoutes',
            new_name='BusRoutes',
        ),
    ]
