# Generated by Django 4.0.5 on 2022-10-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0004_rename_trainroutes_busroutes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusRoutes',
            new_name='BusRoute',
        ),
    ]
