# Generated by Django 4.0.5 on 2022-10-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0006_schooldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_periode', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
