# Generated by Django 4.0.5 on 2022-10-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0007_passform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passform',
            name='time_periode',
        ),
        migrations.AddField(
            model_name='passform',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
