# Generated by Django 4.0.5 on 2022-10-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0013_passform_time_periode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_time', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
