# Generated by Django 4.0.5 on 2022-10-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0014_subtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtime',
            name='sub_price',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subtime',
            name='sub_time',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
