# Generated by Django 4.0.5 on 2022-10-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0015_subtime_sub_price_alter_subtime_sub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtime',
            name='sub_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtime',
            name='sub_time',
            field=models.IntegerField(null=True),
        ),
    ]
