# Generated by Django 4.0.5 on 2022-10-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0016_alter_subtime_sub_price_alter_subtime_sub_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(blank=True, max_length=100, null=True)),
                ('place_district', models.CharField(blank=True, max_length=100, null=True)),
                ('place_state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
