# Generated by Django 4.0.5 on 2022-10-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0018_remove_busroute_districts_remove_busroute_from_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='end_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='ksrtc.places'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='route_places',
            field=models.ManyToManyField(related_name='betweenplace', to='ksrtc.places'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='start_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='ksrtc.places'),
        ),
    ]
