# Generated by Django 4.0.5 on 2022-10-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0019_busroute_end_place_busroute_route_places_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
