# Generated by Django 4.0.5 on 2022-10-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0020_rename_places_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Places',
        ),
    ]
