# Generated by Django 4.0.5 on 2022-10-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0021_rename_place_places'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
