# Generated by Django 4.0.5 on 2022-10-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0022_rename_places_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusRoute',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
