# Generated by Django 4.0.5 on 2022-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0024_place_busroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='Route_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
