# Generated by Django 4.0.5 on 2022-10-16 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_schooldetail'),
        ('ksrtc', '0025_busroute_route_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolDetail',
        ),
        migrations.RemoveField(
            model_name='subtime',
            name='sub_price',
        ),
        migrations.AddField(
            model_name='passform',
            name='adhaar_image',
            field=models.ImageField(default=None, null=True, upload_to='static/ksrtcimage/adhaar'),
        ),
        migrations.AddField(
            model_name='passform',
            name='adhaar_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='passform',
            name='end_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pass_end', to='ksrtc.place'),
        ),
        migrations.AddField(
            model_name='passform',
            name='idimage',
            field=models.ImageField(default=None, null=True, upload_to='static/ksrtcimage/idimage'),
        ),
        migrations.AddField(
            model_name='passform',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='passform',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='passform',
            name='profileimage',
            field=models.ImageField(default=None, null=True, upload_to='static/kstrcimage/profileimage'),
        ),
        migrations.AddField(
            model_name='passform',
            name='school_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.schooldetail'),
        ),
        migrations.AddField(
            model_name='passform',
            name='start_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pass_start', to='ksrtc.place'),
        ),
        migrations.AlterField(
            model_name='passform',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passform',
            name='age',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='passform',
            name='time_periode',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='ksrtc.subtime'),
        ),
    ]
