# Generated by Django 4.1.2 on 2022-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0026_delete_schooldetail_remove_subtime_sub_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtime",
            name="sub_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
