# Generated by Django 4.1.2 on 2022-11-11 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0028_alter_passform_adhaar_image_alter_passform_idimage_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="subtime", name="sub_name",),
    ]
