# Generated by Django 4.1.2 on 2022-11-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0029_remove_subtime_sub_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtime",
            name="sub_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
