# Generated by Django 4.1.2 on 2023-03-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0032_passform_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passform",
            name="adhaar_image",
            field=models.ImageField(
                default=None, null=True, upload_to="static/ksrtcimage/adhaar"
            ),
        ),
        migrations.AlterField(
            model_name="passform",
            name="idimage",
            field=models.ImageField(
                default=None, null=True, upload_to="static/ksrtcimage/idimage"
            ),
        ),
        migrations.AlterField(
            model_name="passform",
            name="profileimage",
            field=models.ImageField(
                default=None, null=True, upload_to="static/ksrtcimage/profileimage"
            ),
        ),
    ]
