# Generated by Django 4.1.2 on 2023-03-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0034_remove_passform_adhaar_image_remove_passform_idimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passform',
            name='adhaar_image',
            field=models.ImageField(default=None, null=True, upload_to='static/ksrtcimage/adhaar'),
        ),
        migrations.AddField(
            model_name='passform',
            name='idimage',
            field=models.ImageField(default=None, null=True, upload_to='static/ksrtcimage/idimage'),
        ),
        migrations.AddField(
            model_name='passform',
            name='profileimage',
            field=models.ImageField(default=None, null=True, upload_to='static/ksrtcimage/profileimage'),
        ),
    ]
