# Generated by Django 4.1.2 on 2023-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0035_passform_adhaar_image_passform_idimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passform',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passform',
            name='adhaar_image',
            field=models.ImageField(default=None, null=True, upload_to='ksrtcimage/adhaar'),
        ),
        migrations.AlterField(
            model_name='passform',
            name='idimage',
            field=models.ImageField(default=None, null=True, upload_to='ksrtcimage/idimage'),
        ),
        migrations.AlterField(
            model_name='passform',
            name='profileimage',
            field=models.ImageField(default=None, null=True, upload_to='ksrtcimage/profileimage'),
        ),
    ]
