# Generated by Django 4.1.2 on 2023-03-02 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ksrtc", "0036_alter_passform_address_alter_passform_adhaar_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="passform",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
