# Generated by Django 4.1.2 on 2023-03-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0041_alter_passform_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="passform",
            name="bus_rate",
            field=models.IntegerField(null=True),
        ),
    ]
