# Generated by Django 4.1.2 on 2023-03-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0042_passform_bus_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="passform",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
