# Generated by Django 4.1.2 on 2023-03-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0043_passform_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="passform",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="passform",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="passform",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
