# Generated by Django 4.1.2 on 2023-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0044_passform_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passform",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="passform",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="passform",
            name="razorpay_signature",
        ),
        migrations.AddField(
            model_name="passform",
            name="amount",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="passform",
            name="order_id",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
