# Generated by Django 4.1.2 on 2023-03-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0045_remove_passform_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passform",
            name="amount",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="passform",
            name="order_id",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
