# Generated by Django 4.1.2 on 2023-03-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0046_alter_passform_amount_alter_passform_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passform",
            name="amount",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="passform",
            name="order_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
