# Generated by Django 4.1.2 on 2023-03-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0047_alter_passform_amount_alter_passform_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passform",
            name="amount",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="passform",
            name="order_id",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
