# Generated by Django 4.1.2 on 2023-03-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0048_alter_passform_amount_alter_passform_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passform",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=20, editable=False, max_digits=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="passform",
            name="order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
