# Generated by Django 4.1.2 on 2023-03-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0049_alter_passform_amount_alter_passform_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passform",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
