# Generated by Django 4.1.2 on 2023-03-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0050_alter_passform_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='passform',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passform',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
