# Generated by Django 4.1.2 on 2023-03-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0052_passform_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='passform',
            name='verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='passform',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
