# Generated by Django 4.1.2 on 2023-03-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0053_passform_verification_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passform",
            name="verification_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
