# Generated by Django 4.1.7 on 2023-04-13 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ksrtc", "0055_passform_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_number", models.IntegerField(blank=True, null=True)),
                (
                    "Route_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buses_route",
                        to="ksrtc.busroute",
                    ),
                ),
            ],
        ),
    ]
