from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name='trainadmin'),
    path('schoolregister/', views.SchoolRegisterPage, name='tschoolregister'),
    path('school/', views.SchoolPage, name='tschool'),
    path('trainplace/', views.TrainPlacePage, name='ttrainplace'),
    path('trainroute/', views.TrainRoutePage, name='ttrainroute'),
    path('traintime/', views.TrainSubTimes, name='ttraintime'),
    path('tpass/', views.TPassPage, name='ttpass'),
    # path('bpass/', views.BPassPage, name='bpass'),
    path('tspass/', views.TSPassPage, name='ttspass'),
    # path('bpassedit/<str:pk>/', views.BPassEditPage, name='bpassedit'),
    path('tpassedit/<str:pk>/', views.TPassEditPage, name='ttpassedit'),
    path('tspassedit/<str:pk>/', views.TSPassEditPage, name='ttspassedit'),
    # path('deletebpass/<str:pk>/', views.DeleteBPass, name='deletebpass'),
    path('deletetpass/<str:pk>/', views.DeleteTPass, name='tdeletetpass'),
    path('deletetspass/<str:pk>/', views.DeleteTSPass, name='tdeletetspass'),
    # path('busplace/', views.BusPlacePage, name='busplace'),
    # path('busplaceregister/', views.BusPlaceRegister, name='busplaceregister'),
    path('trainplaceregister/', views.TrainPlaceRegister, name='ttrainplaceregister'),
    path('schooledit/<str:pk>/', views.SchoolEditPage, name='tschooledit'),
    # path('busplaceedit/<str:pk>/', views.BusPlaceEditPage, name='busplaceedit'),
    path('trainrouteregister/', views.TrainRouteRegister, name='ttrainrouteregister'),
    path('traintimeregister/', views.TrainTimeRegister, name='ttraintimeregister'),
    # path('bustimeregister/', views.BusTimeRegister, name='bustimeregister'),
    path('trainplaceedit/<str:pk>/', views.TrainPlaceEditPage, name='ttrainplaceedit'),
    path('trainrouteedit/<str:pk>/', views.TrainRouteEditPage, name='ttrainrouteedit'),
    path('traintimeedit/<str:pk>/', views.TrainTimeEditPage, name='ttraintimeedit'),
    # path('bustimeedit/<str:pk>/', views.BusTimeEditPage, name='bustimeedit'),
    path('deletetrainroute/<str:pk>/', views.DeleteTrainRoute, name='tdeletetrainroute'),
    path('deletetraintime/<str:pk>/', views.DeleteTrainTime, name='tdeletetraintime'),
    # path('deletebustime/<str:pk>/', views.DeleteBusTime, name='deletebustime'),
    # path('trainedit/<str:pk>/', views.TrainEditPage, name='trainedit'),
    # path('busedit/<str:pk>/', views.BusEditPage, name='busedit'),
    path('deletetrainplace/<str:pk>/', views.DeleteTrainPlace, name='tdeletetrainplace'),
    # path('deletebusplace/<str:pk>/', views.DeleteBusPlace, name='deletebusplace'),
    # path('deletebus/<str:pk>/', views.DeleteBusAdmin, name='deletebus'),
    # path('deletetrain/<str:pk>/', views.DeleteTrainAdmin, name='deletetrain'),
    path('deleteschool/<str:pk>/', views.DeleteSchool, name='tdeleteschool'),
]