# Generated by Django 4.0.5 on 2022-10-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='mobile',
        ),
        migrations.AddField(
            model_name='form',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
