# Generated by Django 4.0.5 on 2022-10-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_form_mobile_form_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
