# Generated by Django 4.0.5 on 2022-10-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_form_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='address',
        ),
    ]
