# Generated by Django 4.0.5 on 2022-10-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_form_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form',
        ),
    ]
