# Generated by Django 4.0.5 on 2022-10-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_schooldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='school_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
