# Generated by Django 4.0.5 on 2022-10-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0002_remove_trainroutes_from_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainroutes',
            name='from_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
