# Generated by Django 4.0.5 on 2022-10-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0004_trainroutes_to_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainRoutes',
            new_name='TrainRoute',
        ),
    ]
