# Generated by Django 4.0.5 on 2022-10-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0006_schooldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_periode', models.CharField(blank=True, choices=[('onemonth', 'onemonth'), ('threemonths', 'threemonths'), ('sixmonths', 'sixmonths'), ('oneyear', 'oneyear')], max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(blank=True, max_length=100, null=True)),
                ('place_district', models.CharField(blank=True, max_length=100, null=True)),
                ('place_state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_time', models.IntegerField(null=True)),
                ('sub_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='trainroute',
            old_name='from_place',
            new_name='Route_name',
        ),
        migrations.RemoveField(
            model_name='trainroute',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='trainroute',
            name='states',
        ),
        migrations.RemoveField(
            model_name='trainroute',
            name='to_place',
        ),
        migrations.AddField(
            model_name='trainroute',
            name='end_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='irctc.place'),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='route_places',
            field=models.ManyToManyField(related_name='betweenplace', to='irctc.place'),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='start_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='irctc.place'),
        ),
    ]
