# Generated by Django 4.0.5 on 2022-10-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0007_passform_place_subtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPassForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_periode', models.CharField(blank=True, choices=[('onemonth', 'onemonth'), ('threemonths', 'threemonths'), ('sixmonths', 'sixmonths'), ('oneyear', 'oneyear')], max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
