# Generated by Django 4.1.2 on 2022-11-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irctc", "0010_rename_passform_trainpassform_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainplace",
            old_name="place_district",
            new_name="train_place_district",
        ),
        migrations.RenameField(
            model_name="trainplace", old_name="place_name", new_name="train_place_name",
        ),
        migrations.RenameField(
            model_name="trainplace",
            old_name="place_state",
            new_name="train_place_state",
        ),
        migrations.RenameField(
            model_name="trainroute", old_name="end_place", new_name="train_end_place",
        ),
        migrations.RenameField(
            model_name="trainroute", old_name="Route_name", new_name="train_route_name",
        ),
        migrations.RenameField(
            model_name="trainroute",
            old_name="route_places",
            new_name="train_route_places",
        ),
        migrations.RenameField(
            model_name="trainroute",
            old_name="start_place",
            new_name="train_start_place",
        ),
    ]
