# Generated by Django 4.1.2 on 2022-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "irctc",
            "0011_rename_place_district_trainplace_train_place_district_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trainsubtime",
            name="sub_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
