# Generated by Django 4.1.2 on 2022-11-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irctc", "0012_trainsubtime_sub_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainpassform",
            name="adhaar_image",
            field=models.ImageField(
                default=None, null=True, upload_to="{% static 'irctcimage/adhaar/ %}"
            ),
        ),
        migrations.AlterField(
            model_name="trainpassform",
            name="profileimage",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="{% static 'irctcimage/profileimage/ %}",
            ),
        ),
    ]
