# Generated by Django 4.1.2 on 2022-11-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irctc", "0014_alter_trainpassform_adhaar_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainstudentpassform",
            name="adhaar_image",
            field=models.ImageField(
                default=None, null=True, upload_to="users/static/irctcimage/adhaar"
            ),
        ),
        migrations.AlterField(
            model_name="trainstudentpassform",
            name="idimage",
            field=models.ImageField(
                default=None, null=True, upload_to="users/static/irctcimage/idimage"
            ),
        ),
        migrations.AlterField(
            model_name="trainstudentpassform",
            name="profileimage",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="users/static/irctcimage/profileimage",
            ),
        ),
    ]
