# Generated by Django 4.1.2 on 2023-03-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0015_alter_trainstudentpassform_adhaar_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainpassform',
            name='adhaar_image',
        ),
        migrations.RemoveField(
            model_name='trainpassform',
            name='profileimage',
        ),
    ]
