# Generated by Django 4.1.2 on 2023-03-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0016_remove_trainpassform_adhaar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainpassform',
            name='adhaar_image',
            field=models.ImageField(default=None, null=True, upload_to='irctcimage/adhaar'),
        ),
        migrations.AddField(
            model_name='trainpassform',
            name='profileimage',
            field=models.ImageField(default=None, null=True, upload_to='irctcimage/profileimage'),
        ),
    ]
