# Generated by Django 4.1.2 on 2023-03-03 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("irctc", "0017_trainpassform_adhaar_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainpassform",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
