# Generated by Django 4.1.7 on 2023-03-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irctc", "0018_trainpassform_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainstudentpassform",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainstudentpassform",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainstudentpassform",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trainstudentpassform",
            name="order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trainstudentpassform",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trainstudentpassform",
            name="payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trainstudentpassform",
            name="signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trainstudentpassform",
            name="train_rate",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="trainstudentpassform",
            name="verification_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
