# Generated by Django 4.1.7 on 2023-03-29 16:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("irctc", "0019_trainstudentpassform_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainstudentpassform",
            name="dob",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="trainstudentpassform",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
